import { StyleSheet,Dimensions } from 'react-native';
const bgColor='#00997a';
const grayColor="#a6a6a6"
const {width,height}=Dimensions.get('window');
const styles=StyleSheet.create({
    contianerDrawer:{
        flex:1,
        backgroundColor:bgColor
    },
    headerDrawer:{
        flex:3,
        justifyContent:'center',
        alignItems:'center'
    },
    itemDrawer:{
        backgroundColor:'white',
        marginTop:10,
        justifyContent:'center',
        paddingHorizontal:10,
        borderRadius:10
    },

    //img
    imgAvatar:{
        width:180,
        height:180,
        borderRadius:90,
        borderColor:'white',
        borderWidth:1
    },
    imgIcon:{
        width:30,
        height:30
    }, 
   
    imgStyleItemPro:{
        height:180,
        width:width/2-40,
        marginBottom:10
    },
    imgStyleBanner:{
        height:height/3-50,
        width:width-60,
    },
    imgProducDetail:{
        height:220,
        width:width/2-40,
        margin:5
    },



//Txt
    txtRedBig:{
        color:'#cc0066',
        fontSize:20
    },
    txtRed:{
        color:'#cc0066'
    },  
    txtBigWhite:{
        color:'white',
        fontSize:22,
    },
    txtTitle:{
        fontSize:22,
        textTransform:'uppercase',
        color:'#a6a6a6',
        marginHorizontal:10,
        marginTop:5
    },
    txtNamePro:{
        fontSize:18,
        textTransform:'uppercase',
        color:'#a6a6a6'
    },
    txtPrice:{
        fontSize:18,
        textTransform:'uppercase',
        color:'#cc0066'
    },
    txtBtn:{
        fontSize:18,
        color:'white',
        textTransform:'uppercase',
        
    },
    txtWhite:{
        color:'white',
        fontSize:18,
        textAlign:'center'
    },
    txtLeftOrder:{
        color:'#a6a6a6',
        fontSize:18,
        fontWeight:'bold'
    },
    txtOrderId:{
        color:bgColor,
        fontSize:18
    },
    txtBigBlack:{
        fontSize:18,
        color:'black',
        fontWeight:'bold'
    },
    

    containerHeader:{
        height:90,
        backgroundColor:bgColor,
        paddingHorizontal:10,
        paddingVertical:10
    },
    rowBetween:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
        },
       rowCenter:{
            flexDirection:'row',
            justifyContent:'center',
        },
    txtInputHeader:{
        padding:5,
        backgroundColor:'white',
        paddingHorizontal:20,
        fontSize:18,
        
    },
    txtInputSign:{
        paddingVertical:10,
        backgroundColor:'white',
        paddingHorizontal:20,
        fontSize:18,
        borderRadius:20,
        marginVertical:10
    },
   
    containerCollection:{
        height:height/3,
        backgroundColor:'#ffffff',
        marginHorizontal:10,
        marginTop:10,
        elevation:5
        
    },

    boxBanner:{
        flex:1,
        alignItems:'center'
    },
    containerTopProfuct:{
        backgroundColor:'#ffffff',
        marginHorizontal:5,
        marginTop:10,
        elevation:5,

    },
    containerItem:{
        height:250,
        width:width/2-40,
        marginBottom:20,
        elevation:1,
        marginHorizontal:10,
        borderBottomColor:'#a6a6a6',
        alignItems:'center'
        
    },
    containerSile:{
        width:width-40,
        height:height/3-50
    },
    containerSignIn:{
        flex:1,
        marginTop:50,
        marginHorizontal:30
    },
    btnSign:{
        paddingVertical:10,
        borderRadius:20,
        borderColor:'white',
        borderWidth:1,
        justifyContent:'center',
        alignItems:'center',
        marginVertical:10,
    },
    btnLeft:{
        flex:1,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
        borderTopLeftRadius:20,
        borderBottomLeftRadius:20,

    },
    btnRight:{
        flex:1,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
        borderTopRightRadius:20,
        borderBottomRightRadius:20
    },
    btnIfo:{
        backgroundColor:bgColor,
        paddingVertical:10,
        padding:5,
        justifyContent:'center',
        alignContent:'center',
        borderRadius:20,
        marginTop:10
    },
    footerAuthen:{
        height:100,
        flexDirection:'row',
        marginHorizontal:30
    },
    headerChangeInfo:{
        height:50,
        backgroundColor:bgColor,
        justifyContent:'space-between',
        flexDirection:'row',
       alignItems:'center',
       paddingHorizontal:10
    },
    containerOrder:{
        height:height/4,
        backgroundColor:'white',
        margin:10,
        elevation:3,
        padding:10,
        justifyContent:'center'
        
    },
    containerDetail:{
        padding:10,
        margin:10,
        backgroundColor:'white',
        flex:1,
        elevation:2,
        paddingHorizontal:20
    },
    iconColor:{
        width:25,
        height:25,
        borderRadius:25/2,
        backgroundColor:'khaki',
        marginHorizontal:10,
        borderColor:'red',
        borderWidth:1
    },
    itemListProduct:{
        padding:10,
        borderBottomColor:'#f2f2f2',
        borderBottomWidth:1,
        marginTop:10
    },
    boxImgList:{
        width:110
    },
    rightListProduct:{
        flexDirection:'column',
        justifyContent:'space-around',
        
    }


})

export default styles;